version: "3.9"

services:
  api01: &api
    image: ptrecenti/crebito:latest
    entrypoint:
      - "/crebito"
      - "-Xms128m"
      - "-Xmx128m"
    hostname: api01
    ports:
      - "8081:8080"
    environment:
      - SCALE_FACTOR=1
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=rinha
      - DB_USER=rinha
      - DB_PASS=rinha
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    command: postgres -c max_connections=128 -c checkpoint_timeout=600 -c max_wal_size=4096 -c full_page_writes=0 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "267MB"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "rinha" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  app-network: